[package]
name = "fxread"
version = "0.1.0"
edition = "2021"
description = "A barebones fastx reader for rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1"
anyhow = "1"
